import json
import os
import re
import time
from g4f.client import Client
from config import HISTORY_FILE, MAX_HISTORY, G4F_MODELS, G4F_MAX_RETRIES
from prompt import SYSTEM_PROMPT


client = Client()

# Patterns to strip provider ads/spam from responses
_AD_PATTERNS = [
    re.compile(r"Need proxies cheaper than the market\?[^\n]*", re.IGNORECASE),
    re.compile(r"https?://op\.wtf[^\n]*", re.IGNORECASE),
    re.compile(r"Cheap proxies[^\n]*", re.IGNORECASE),
    re.compile(r"\[.*?sponsored.*?\]", re.IGNORECASE),
    re.compile(r"Generated by .*?AI[^\n]*", re.IGNORECASE),
]


def _clean_response(text: str) -> str:
    for pattern in _AD_PATTERNS:
        text = pattern.sub("", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()

PROMPT_PREFIX = (
    "[Roleplay instructions - follow strictly]\n"
    + SYSTEM_PROMPT
    + "\n[End instructions. Now respond in character as Yuki]\n\n"
)


def load_history() -> dict:
    if os.path.exists(HISTORY_FILE):
        try:
            with open(HISTORY_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except (json.JSONDecodeError, IOError):
            return {}
    return {}


def save_history(history: dict) -> None:
    with open(HISTORY_FILE, "w", encoding="utf-8") as f:
        json.dump(history, f, ensure_ascii=False, indent=2)


chat_history: dict = load_history()


def get_user_history(user_id: int) -> list:
    return chat_history.get(str(user_id), [])


def add_message(user_id: int, role: str, content: str) -> None:
    key = str(user_id)
    if key not in chat_history:
        chat_history[key] = []
    chat_history[key].append({"role": role, "content": content})
    if len(chat_history[key]) > MAX_HISTORY:
        chat_history[key] = chat_history[key][-MAX_HISTORY:]
    save_history(chat_history)


def clear_history(user_id: int) -> None:
    key = str(user_id)
    if key in chat_history:
        del chat_history[key]
        save_history(chat_history)


def _build_messages(user_id: int) -> list:
    history = get_user_history(user_id)
    if not history:
        return []

    messages = []
    for i, msg in enumerate(history):
        if i == 0 and msg["role"] == "user":
            messages.append({
                "role": "user",
                "content": PROMPT_PREFIX + msg["content"],
            })
        else:
            messages.append({"role": msg["role"], "content": msg["content"]})

    return messages


def _try_request(messages: list, model: str) -> str | None:
    try:
        response = client.chat.completions.create(
            model=model,
            messages=messages,
            temperature=1.0,
            max_tokens=300,
        )
        if response and response.choices:
            text = response.choices[0].message.content
            if text:
                text = _clean_response(text)
                if len(text) > 0:
                    return text
    except Exception as e:
        print(f"[G4F] {model} error: {e}")
    return None


def get_response(user_id: int, message: str) -> str | None:
    add_message(user_id, "user", message)

    messages = _build_messages(user_id)
    if not messages:
        return None

    for attempt in range(G4F_MAX_RETRIES):
        for model in G4F_MODELS:
            result = _try_request(messages, model)
            if result:
                add_message(user_id, "assistant", result)
                return result
        print(f"[G4F] All models failed, attempt {attempt + 1}/{G4F_MAX_RETRIES}")
        time.sleep(2)

    print("[G4F] All retries exhausted")
    return None
